version: '3.9'

services:
  user-service-db:
    container_name: 'user-service-db'
    image: 'postgres:12'
    restart: always
    ports:
      - 15432:5432
    networks:
      - booking-core
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: core_user
      POSTGRES_PASSWORD: core
    volumes:
      - postgres-data:/var/lib/postgresql/data
  user-service-app:
    container_name: 'user-service'
    build: .
    ports:
      - 8081:8081
      - 5001:5001
    networks:
      - booking-core
    environment:
      _JAVA_OPTIONS: >
        -Xdebug
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5001
      DATABASE_URL: postgresql://user-service-db:15432/user_service
      DATABASE_USERNAME: core_user
      DATABASE_PASSWORD: core
    depends_on:
      - user-service-db
volumes:
  postgres-data:
networks:
  booking-core:
    name: booking-core
    driver: bridge